retry_count: 5
google:
  client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  scope: 'email,https://www.googleapis.com/auth/calendar'
goo:
  app_id: <%= ENV["GOO_APP_ID"] %>
line:
  channel_secret: <%= ENV["LINE_CHANNEL_SECRET"] %>
  channel_token: <%= ENV["LINE_CHANNEL_TOKEN"] %>
twitter:
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
mecab:
  mecab_dict_index_path: /usr/local/libexec/mecab/mecab-dict-index
  ipadic_path: /usr/local/lib/mecab/dic/ipadic
  neologd: /usr/local/lib/mecab/dic/mecab-ipadic-neologd/
  userdic: /usr/local/lib/mecab/dic/custom.dic
